import Head from 'next/head';

import AppNavBar from '../components/AppNavBar';
import AppCardBullets from '../components/AppCardBullets';

export default function Home() {
  
  let title = 'Meu Primeiro WebAPP';

  const bullets_today = [
    {type: 'event', title: ' Este é um exemplo de componentização React'},
    {type: 'task', title: ' As linhas abaixo fazem parte do AppCardBullets'}
  ];
  const bullets_tomorrow = [
    {type: 'task', title: 'Exemplo de linha da lista 1'},
    {type: 'task', title: 'Exemplo de linha da lista 2'}
  ];

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
          <AppNavBar title={title} />
          {bullets_today.map(item => <h3>{item.type} - {item.title}</h3>)}
          <p>{bullets_today[0].type} - {bullets_today[0].title}</p> 
          <AppCardBullets date={"21/09/2021"} bullets={bullets_today}/>
          <AppCardBullets date={"28/09/2021"} bullets={bullets_tomorrow}/>
      </main>
    </div>   
  )
}
